name: Auto-Update Anime 24/7 M3U Playlist

on:
  schedule:
    - cron: "0 6 * * *"  # daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update-anime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false  # required for PAT auth

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Generator Script
        run: python anime_247_generator.py

      - name: Push changes
        run: |
          git config --global user.name "Syntax404errorrr"
          git config --global user.email "syntax404errorrr@users.noreply.github.com"
          git remote set-url origin https://$PAT_TOKEN@github.com/Syntax404errorrr/HIDDEN.git
          git add output/anime_247.m3u
          git commit -m "ðŸ”„ Auto-update: anime_247.m3u" || echo "No changes"
          git push origin main          
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
