name: Auto Update Sflix Playlist

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 4 AM UTC
  workflow_dispatch:

jobs:
  update-sflix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false  # important to use PAT

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Scraper
        run: python smart_sflix_scraper_playwright.py

      - name: Commit Updated Playlist
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "Syntax404errorrr"
          git config --global user.email "syntax404errorrr@users.noreply.github.com"
          git remote set-url origin https://$PAT_TOKEN@github.com/Syntax404errorrr/HIDDEN.git
          git add output/movies.m3u
          git diff --cached --quiet || git commit -m "ðŸ”„ Auto-update: movies.m3u"
          git push origin main
