name: Update Playlist

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important to allow pulling latest commits
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Merger Script
        run: |
          python mgenzmiptvpremium.py

      - name: Configure Git
        run: |
          git config --global user.name "Syntax404errorrr"
          git config --global user.email "syntax404errorrr@users.noreply.github.com"

      - name: Pull latest changes (IMPORTANT)
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/Syntax404errorrr/HIDDEN.git
          git pull origin main --rebase --strategy-option theirs || true

      - name: Commit Changes
        run: |
          git add UMIPTVPREMIUM.m3u
          git commit -m "ðŸ”„ Auto-update: UMIPTVPREMIUM.m3u" || echo "No changes"

      - name: Push Changes
        run: |
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
